apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: authentication-microservice
objects:
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    generation: 2
    labels:
      app: authsvc
    name: authsvc
  spec:
    replicas: 2
    revisionHistoryLimit: 10
    selector:
      app: authsvc
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: authsvc
        name: authsvc
      spec:
        containers:
        - env:
          - name: UID
            valueFrom:
              secretKeyRef:
                key: UID
                name: cumulusbankauth
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                key: PASSWORD
                name: cumulusbankauth
          - name: SECRET
            valueFrom:
              secretKeyRef:
                key: SECRET
                name: cumulusbankauth
          - name: DATABASE
            valueFrom:
              configMapKeyRef:
                key: DATABASE
                name: cumulusbankauth
          - name: PORT
            valueFrom:
              configMapKeyRef:
                key: PORT
                name: cumulusbankauth
          - name: HOST
            valueFrom:
              configMapKeyRef:
                key: HOST
                name: cumulusbankauth
          - name: PROTOCOL
            valueFrom:
              configMapKeyRef:
                key: PROTOCOL
                name: cumulusbankauth
          image: docker-registry.default.svc:5000/kubeapp/authsvc@sha256:beca005fa2f96473dc3f48f70de424b812e88d2f1186206343bac6660aec8c84
          imagePullPolicy: Always
          lifecycle:
            preStop:
              exec:
                command:
                - /bin/bash -c sleep 20
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 3004
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 300
            successThreshold: 1
            timeoutSeconds: 2
          name: authsvc
          ports:
          - containerPort: 3004
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 3004
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          resources:
            limits:
              cpu: 80m
              memory: 200Mi
            requests:
              cpu: 50m
              memory: 150Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - authsvc
        from:
          kind: ImageStreamTag
          name: authsvc:latest
          namespace: kubeapp
        lastTriggeredImage: docker-registry.default.svc:5000/kubeapp/authsvc@sha256:beca005fa2f96473dc3f48f70de424b812e88d2f1186206343bac6660aec8c84
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      app: authsvc
    name: authsvc
  spec:
    ports:
    - name: authsvc
      port: 3004
      protocol: TCP
      targetPort: 3004
    selector:
      app: authsvc
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  data:
    PASSWORD: YWRtaW4=
    SECRET: aGVsbG8=
    UID: YWRtaW4=
  kind: Secret
  metadata:
    creationTimestamp: null
    labels:
      app: authsvc
    name: cumulusbankauth
  type: Opaque
- apiVersion: v1
  data:
    DATABASE: SAMPLE
    HOST: mariadb.kubeapp
    PORT: "3306"
    PROTOCOL: TCPIP
  kind: ConfigMap
  metadata:
    creationTimestamp: null
    labels:
      app: authsvc
    name: cumulusbankauth
- apiVersion: autoscaling/v1
  kind: HorizontalPodAutoscaler
  metadata:
    annotations:
      autoscaling.alpha.kubernetes.io/conditions: '[{"type":"AbleToScale","status":"False","lastTransitionTime":"2019-07-29T14:50:23Z","reason":"FailedGetScale","message":"the
        HPA controller was unable to get the target''s current scale: deployments/scale.extensions
        \"authsvc\" not found"}]'
    creationTimestamp: null
    labels:
      app: authsvc
    name: authsvcmicroservicehpa
  spec:
    maxReplicas: 10
    minReplicas: 2
    scaleTargetRef:
      apiVersion: extensions/v1beta1
      kind: Deployment
      name: authsvc
    targetCPUUtilizationPercentage: 50
  status:
    currentReplicas: 0
    desiredReplicas: 0
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: null
    labels:
      app: authsvc
    name: authsvc
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: authsvc:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        ref: master
        uri: https://github.com/cumulus-bank/authentication-mariadb.git
      type: Git
    strategy:
      dockerStrategy: {}
      type: Docker
    successfulBuildsHistoryLimit: 5
    triggers:
    - type: ConfigChange
    - generic:
        secret: secret3
      type: Generic
    - github:
        secret: secret4
      type: GitHub
  status:
    lastVersion: 0
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      description: Keeps track of changes in the application image
    creationTimestamp: null
    generation: 1
    labels:
      app: authsvc
    name: authsvc
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: docker-registry.default.svc:5000/kubeapp/authsvc:latest
      generation: null
      importPolicy: {}
      name: latest
      referencePolicy:
        type: ""
  status:
    dockerImageRepository: ""
