apiVersion: apps/v1
kind: Deployment
metadata:
  name: cumulusBankAuthSvc
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cumulusBankAuthSvc
  template:
    metadata:
      labels:
        name: cumulusBankAuthSvc
    spec:
      serviceAccountName: cumulusBankAuthSvc
      containers:
        - name: cumulusBankAuthSvc
          # Replace this with the built image name
          image: REPLACE_IMAGE
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "cumulusBankAuthSvc"
