replicaCount: 2
namespace: kubeapp

mariadb:
  database: "SAMPLE"
  host: "mariadb.kubeapp"
  uid: YWRtaW4=
  password: YWRtaW4=
  secret: aGVsbG8=
metadata:
 name: auth-svc 
 label: auth-svc
readinessProbe:
  path: /healthz
  port: 3004
  initialDelaySeconds: 10
  timeoutSeconds: 2
  periodSeconds: 10

livenessProbe:
  path: /healthz
  port: 3004
  initialDelaySeconds: 10
  timeoutSeconds: 2
  periodSeconds: 300
image:
  name: auth-svc
  imageName: "auth-svc" 
  imagePullPolicy: Always
  ports:
    containerPort: 3004
  requests:
    cpu: "50m"
    memory: "150Mi"
  limits:
    cpu: "80m"
    memory: "200Mi"
  maxSurge: 1
  maxUnavailable: 0
  lifecycle:
    preStop:
      command: ["/bin/bash", "-c", "sleep 20"]
  
hpa:
  metadata:
    name: auth-svcmicroservicehpa
  spec:
    maxReplicas: 10
    minReplicas: 2
  metrics:
    pods:
      targetAverageValue: 30
    resource:
      name: cpu
      targetAverageUtilization: 50
    memory:
      targetAverageUtilization: 50
  scaleTargetRef:  
    name: auth-svc

envOfSecrets:
  envUID:
    name: UID
    secretKeyRef:
      name: cumulusbankauth
      key: UID
  envPASSWORD:
    name: PASSWORD
    secretKeyRef:
      name: cumulusbankauth
      key: PASSWORD
  envSECRET:
    name: SECRET
    secretKeyRef:
      name: cumulusbankauth
      key: SECRET

envOfConfigmaps:
  envNODE_ENV:
    name: NODE_ENV
    configMapKeyRef:
      name: cumulusbankauth
      key: NODE_ENV
  envDATABASE:
    name: DATABASE
    configMapKeyRef:
      name: cumulusbankauth
      key: DATABASE
  envPORT:
    name: PORT
    configMapKeyRef:
      name: cumulusbankauth
      key: PORT
  envHOST:
    name: HOST
    configMapKeyRef:
      name: cumulusbankauth
      key: HOST
  envPROTOCOL:
    name: PROTOCOL
    configMapKeyRef:
      name: cumulusbankauth
      key: PROTOCOL


service:
  serviceMetadata:
    name: auth-svc
    labels:
      app: auth-svc
  selector:
    selectorName: auth-svc
  servicePortConfiguration:
    protocol: TCP
    name: auth-svc
    type: ClusterIP
    port: 3004
    targetPort: 3004


imagestream:
  name:  auth-svc
  label: auth-svc

buildconfig:
  uri: "https://github.com/cumulus-bank/authentication-mariadb.git"
  branch: "master"
  name: "auth-svc"
  imagename: "auth-svc:latest"
  secret1: "sedrfgh"
  secret2: "sedrfgh"


routes:
  host: "auth-svc-kubeapp.apps.9.30.210.207.nip.io"
  targetPort: 3004
  name: auth-svc
  weight: 100


nameOverride: ""
fullnameOverride: ""