apiVersion: v1
kind: ConfigMap
metadata:
  name: cumulusbankauth
  namespace: kubeapp
  labels:
    app: {{ .Values.metadata.name }} 
data:
  DATABASE: SAMPLE
  PORT: '3306'
  HOST: 'mariadb.kubeapp'
  PROTOCOL: TCPIP