apiVersion: v1
kind: Secret
metadata:
  name: cumulusbankauth
  namespace: kubeapp
  labels:
    app: {{ .Values.metadata.name }} 
type: Opaque
data:
  UID: YWRtaW4=
  PASSWORD: YWRtaW4=
  SECRET: aGVsbG8=